"""Frontier design tokens — the palette every planviz figure draws in.

Generated by ``scripts/sync_tokens.py`` from the ``openplan-labs/branding``
repository (``tokens/tokens.json``). **Do not edit by hand**: CI regenerates
this file and fails the build if it has drifted from the brand.

The three semantic values are the figure legend, not a chart palette. ``path``
is the solution and the only warm colour in the system; ``frontier`` is the open
list; ``expanded`` is the closed list. A fourth or fifth series in a chart takes
:data:`AGENT_RAMP`, never one of those three.

    >>> from planviz import tokens
    >>> tokens.LIGHT.path
    '#c2472c'
    >>> tokens.get(dark=True).path
    '#e87a5c'
    >>> tokens.LIGHT.agent(2)
    '#7a6f9c'
"""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass

__all__ = [
    "Tokens",
    "LIGHT",
    "DARK",
    "AGENT_RAMP",
    "MARKERS",
    "FONTS",
    "SPEC_VERSION",
    "get",
    "PATH",
    "FRONTIER",
    "EXPANDED",
    "FAINT",
    "LINE",
    "MUTED",
    "BODY",
    "HEADING",
    "BG",
    "BG_RAISED",
]

#: Version of ``branding/tokens/tokens.json`` these values were generated from.
SPEC_VERSION = "1.0.0"

#: Categorical ramp for multi-agent and planner-comparison figures *only*.
#: Deliberately cooler and flatter than ``path`` so no agent out-shouts the
#: solution. Assign by stable index, never by iteration order.
AGENT_RAMP: tuple[str, ...] = (
    "#3d6d8f",
    "#4f8a7b",
    "#7a6f9c",
    "#8a6d5a",
    "#5b7f9e",
    "#6b9a8b",
    "#8f7fae",
    "#9c7f6a",
)

#: Shape is the identity channel that survives greyscale and colour blindness.
#: Past eight agents the hue repeats but the marker does not.
MARKERS: tuple[str, ...] = ("o", "s", "^", "D", "P", "X")

#: Type roles from ``branding/brand/typography.md``.
FONTS = {
    "display": "Libre Franklin",
    "prose": "Charter",
    "mono": "IBM Plex Mono",
}


@dataclass(frozen=True)
class Tokens:
    """One resolved colour scheme — light or dark.

    Every field is a CSS/matplotlib colour string. Prefer the semantic names
    over literals: a figure drawn in these values is on-brand by construction.

        >>> from planviz import tokens
        >>> t = tokens.get(dark=False)
        >>> t.mode, t.path
        ('light', '#c2472c')
    """

    #: ``"light"`` or ``"dark"``.
    mode: str
    #: Page ground. Cool, not cream.
    bg: str
    #: Cards and figure panels — the axes face.
    bg_raised: str
    #: Rules, borders, and obstacles: structure, not data.
    line: str
    #: Ink for titles.
    heading: str
    #: Running text and axis labels.
    body: str
    #: Captions and tick labels.
    muted: str
    #: Unvisited nodes. Not a prose colour.
    faint: str
    #: **The solution.** The only warm value in the system.
    path: str
    #: Translucent wash of :attr:`path`, for highlighted regions.
    path_soft: str
    #: **The open list.**
    frontier: str
    #: **The closed list.** Not a text colour on light (3.60:1).
    expanded: str
    #: Categorical ramp, shared by both modes.
    agents: tuple[str, ...] = AGENT_RAMP

    def agent(self, index: int) -> str:
        """Return the ramp colour for agent ``index``, wrapping past eight.

            >>> from planviz import tokens
            >>> tokens.LIGHT.agent(0) == tokens.AGENT_RAMP[0]
            True
        """
        return self.agents[index % len(self.agents)]

    def marker(self, index: int) -> str:
        """Return the marker for agent ``index`` — the shape channel.

        Changes only once the hue has wrapped, so agent 8 shares agent 0's
        colour but not its mark.

            >>> from planviz import tokens
            >>> tokens.LIGHT.marker(0), tokens.LIGHT.marker(8)
            ('o', 's')
        """
        return MARKERS[(index // len(self.agents)) % len(MARKERS)]

    def agent_colors(self, names: Sequence[str]) -> dict:
        """Map ``names`` to ramp colours by position — stable across re-renders.

            >>> from planviz import tokens
            >>> tokens.LIGHT.agent_colors(["a", "b"])["a"] == tokens.AGENT_RAMP[0]
            True
        """
        return {name: self.agent(i) for i, name in enumerate(names)}

    def sequential(self, name: str = "frontier_seq"):
        """Return the single-hue magnitude colormap: ``expanded`` → ``path``.

        Warm end is expensive, which agrees with the rest of the system. Never
        a rainbow.

            >>> from planviz import tokens
            >>> tokens.LIGHT.sequential().N
            256
        """
        from matplotlib.colors import LinearSegmentedColormap

        return LinearSegmentedColormap.from_list(
            name, [self.expanded, self.path], N=256
        )


#: The light scheme. Light-first: papers, READMEs and notebooks default here.
LIGHT = Tokens(
    mode="light",
    bg="#f2f4f6",
    bg_raised="#ffffff",
    line="#d9dfe4",
    heading="#14181c",
    body="#3c464e",
    muted="#5e6a73",
    faint="#7b8790",
    path="#c2472c",
    path_soft="#c2472c14",
    frontier="#127a78",
    expanded="#6d8298",
)

#: The dark scheme. Not an inversion — each hue was lightened independently
#: until it cleared 4.5:1 on the dark ground while keeping its ordering.
DARK = Tokens(
    mode="dark",
    bg="#12171a",
    bg_raised="#1a2126",
    line="#2a343a",
    heading="#e8edf0",
    body="#aab6bd",
    muted="#7d8b93",
    faint="#59666e",
    path="#e87a5c",
    path_soft="#e87a5c1a",
    frontier="#3fb3ad",
    expanded="#8ba2b7",
)

# Light-first convenience aliases. For dark values use ``DARK.path`` etc.
PATH = LIGHT.path
FRONTIER = LIGHT.frontier
EXPANDED = LIGHT.expanded
FAINT = LIGHT.faint
LINE = LIGHT.line
MUTED = LIGHT.muted
BODY = LIGHT.body
HEADING = LIGHT.heading
BG = LIGHT.bg
BG_RAISED = LIGHT.bg_raised


def get(dark: bool = False) -> Tokens:
    """Return :data:`DARK` when ``dark`` is true, else :data:`LIGHT`.

        >>> from planviz import tokens
        >>> tokens.get(dark=True).mode
        'dark'
    """
    return DARK if dark else LIGHT
