#!/usr/bin/env python3
"""Vendor the Frontier design tokens into the package, or check them for drift.

`planviz` ships the brand's values inside the wheel — ``planviz/tokens.py`` and
``planviz/styles/frontier.mplstyle`` — so a consumer never has to locate the
branding repository at runtime, and a figure rendered on a CI runner with no
network looks exactly like one rendered on a laptop.

The cost of vendoring is drift, so this script is both the generator and the
guard:

.. code-block:: sh

    python scripts/sync_tokens.py            # regenerate from the branding repo
    python scripts/sync_tokens.py --check    # fail if the vendored copy differs
    python scripts/sync_tokens.py --source ../branding   # use a local checkout

``--check`` runs in CI. It fetches
``raw.githubusercontent.com/openplan-labs/branding/main/tokens/`` and fails the
build when what is committed here no longer matches what the brand says.
"""

from __future__ import annotations

import argparse
import difflib
import json
import sys
import urllib.request
from pathlib import Path
from typing import Any

REPO = Path(__file__).resolve().parents[1]
TOKENS_PY = REPO / "planviz" / "tokens.py"
MPLSTYLE = REPO / "planviz" / "styles" / "frontier.mplstyle"

DEFAULT_SOURCE = (
    "https://raw.githubusercontent.com/openplan-labs/branding/main/tokens"
)

# Fields of Tokens, in declaration order, mapped to their key in tokens.json.
_FIELDS = [
    ("bg", "bg"),
    ("bg_raised", "bgRaised"),
    ("line", "line"),
    ("heading", "heading"),
    ("body", "body"),
    ("muted", "muted"),
    ("faint", "faint"),
    ("path", "path"),
    ("path_soft", "pathSoft"),
    ("frontier", "frontier"),
    ("expanded", "expanded"),
]

_HEADER = '''"""Frontier design tokens — the palette every planviz figure draws in.

Generated by ``scripts/sync_tokens.py`` from the ``openplan-labs/branding``
repository (``tokens/tokens.json``). **Do not edit by hand**: CI regenerates
this file and fails the build if it has drifted from the brand.

The three semantic values are the figure legend, not a chart palette. ``path``
is the solution and the only warm colour in the system; ``frontier`` is the open
list; ``expanded`` is the closed list. A fourth or fifth series in a chart takes
:data:`AGENT_RAMP`, never one of those three.

    >>> from planviz import tokens
    >>> tokens.LIGHT.path
    '{light_path}'
    >>> tokens.get(dark=True).path
    '{dark_path}'
    >>> tokens.LIGHT.agent(2)
    '{agent_2}'
"""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass

__all__ = [
    "Tokens",
    "LIGHT",
    "DARK",
    "AGENT_RAMP",
    "MARKERS",
    "FONTS",
    "SPEC_VERSION",
    "get",
    "PATH",
    "FRONTIER",
    "EXPANDED",
    "FAINT",
    "LINE",
    "MUTED",
    "BODY",
    "HEADING",
    "BG",
    "BG_RAISED",
]

#: Version of ``branding/tokens/tokens.json`` these values were generated from.
SPEC_VERSION = "{spec_version}"

#: Categorical ramp for multi-agent and planner-comparison figures *only*.
#: Deliberately cooler and flatter than ``path`` so no agent out-shouts the
#: solution. Assign by stable index, never by iteration order.
AGENT_RAMP: tuple[str, ...] = (
{agent_ramp}
)

#: Shape is the identity channel that survives greyscale and colour blindness.
#: Past eight agents the hue repeats but the marker does not.
MARKERS: tuple[str, ...] = ("o", "s", "^", "D", "P", "X")

#: Type roles from ``branding/brand/typography.md``.
FONTS = {{
{fonts}
}}


@dataclass(frozen=True)
class Tokens:
    """One resolved colour scheme — light or dark.

    Every field is a CSS/matplotlib colour string. Prefer the semantic names
    over literals: a figure drawn in these values is on-brand by construction.

        >>> from planviz import tokens
        >>> t = tokens.get(dark=False)
        >>> t.mode, t.path
        ('light', '{light_path}')
    """

    #: ``"light"`` or ``"dark"``.
    mode: str
    #: Page ground. Cool, not cream.
    bg: str
    #: Cards and figure panels — the axes face.
    bg_raised: str
    #: Rules, borders, and obstacles: structure, not data.
    line: str
    #: Ink for titles.
    heading: str
    #: Running text and axis labels.
    body: str
    #: Captions and tick labels.
    muted: str
    #: Unvisited nodes. Not a prose colour.
    faint: str
    #: **The solution.** The only warm value in the system.
    path: str
    #: Translucent wash of :attr:`path`, for highlighted regions.
    path_soft: str
    #: **The open list.**
    frontier: str
    #: **The closed list.** Not a text colour on light (3.60:1).
    expanded: str
    #: Categorical ramp, shared by both modes.
    agents: tuple[str, ...] = AGENT_RAMP

    def agent(self, index: int) -> str:
        """Return the ramp colour for agent ``index``, wrapping past eight.

            >>> from planviz import tokens
            >>> tokens.LIGHT.agent(0) == tokens.AGENT_RAMP[0]
            True
        """
        return self.agents[index % len(self.agents)]

    def marker(self, index: int) -> str:
        """Return the marker for agent ``index`` — the shape channel.

        Changes only once the hue has wrapped, so agent 8 shares agent 0's
        colour but not its mark.

            >>> from planviz import tokens
            >>> tokens.LIGHT.marker(0), tokens.LIGHT.marker(8)
            ('o', 's')
        """
        return MARKERS[(index // len(self.agents)) % len(MARKERS)]

    def agent_colors(self, names: Sequence[str]) -> dict:
        """Map ``names`` to ramp colours by position — stable across re-renders.

            >>> from planviz import tokens
            >>> tokens.LIGHT.agent_colors(["a", "b"])["a"] == tokens.AGENT_RAMP[0]
            True
        """
        return {{name: self.agent(i) for i, name in enumerate(names)}}

    def sequential(self, name: str = "frontier_seq"):
        """Return the single-hue magnitude colormap: ``expanded`` → ``path``.

        Warm end is expensive, which agrees with the rest of the system. Never
        a rainbow.

            >>> from planviz import tokens
            >>> tokens.LIGHT.sequential().N
            256
        """
        from matplotlib.colors import LinearSegmentedColormap

        return LinearSegmentedColormap.from_list(
            name, [self.expanded, self.path], N=256
        )


#: The light scheme. Light-first: papers, READMEs and notebooks default here.
LIGHT = Tokens(
    mode="light",
{light}
)

#: The dark scheme. Not an inversion — each hue was lightened independently
#: until it cleared 4.5:1 on the dark ground while keeping its ordering.
DARK = Tokens(
    mode="dark",
{dark}
)

# Light-first convenience aliases. For dark values use ``DARK.path`` etc.
PATH = LIGHT.path
FRONTIER = LIGHT.frontier
EXPANDED = LIGHT.expanded
FAINT = LIGHT.faint
LINE = LIGHT.line
MUTED = LIGHT.muted
BODY = LIGHT.body
HEADING = LIGHT.heading
BG = LIGHT.bg
BG_RAISED = LIGHT.bg_raised


def get(dark: bool = False) -> Tokens:
    """Return :data:`DARK` when ``dark`` is true, else :data:`LIGHT`.

        >>> from planviz import tokens
        >>> tokens.get(dark=True).mode
        'dark'
    """
    return DARK if dark else LIGHT
'''


def _read(source: str, name: str) -> str:
    """Return the text of ``name`` from a URL prefix or a local directory."""
    if source.startswith(("http://", "https://")):
        url = f"{source.rstrip('/')}/{name}"
        with urllib.request.urlopen(url, timeout=30) as response:  # noqa: S310
            return response.read().decode("utf-8")
    root = Path(source).expanduser().resolve()
    for candidate in (root / name, root / "tokens" / name):
        if candidate.is_file():
            return candidate.read_text(encoding="utf-8")
    raise SystemExit(f"cannot find {name} under {root}")


def _mpl_color(value: str) -> str:
    """Return a matplotlib-parsable colour for a token value.

    The brand publishes translucent tokens as CSS ``rgba()``, which matplotlib
    cannot read; ``#rrggbbaa`` is the same colour in a form it can.
    """
    if not value.startswith("rgba("):
        return value
    red, green, blue, alpha = (
        part.strip() for part in value[len("rgba(") : -1].split(",")
    )
    channels = (int(red), int(green), int(blue), round(float(alpha) * 255))
    return "#" + "".join(f"{channel:02x}" for channel in channels)


def _scheme(spec: dict, key: str) -> str:
    block: dict[str, Any] = spec[key]
    lines = []
    for field, token in _FIELDS:
        value = _mpl_color(block[token]["value"])
        lines.append(f'    {field}="{value}",')
    return "\n".join(lines)


def render(spec: dict) -> str:
    """Return the full source text of ``planviz/tokens.py`` for ``spec``."""
    ramp = spec["agents"]["value"]
    return _HEADER.format(
        spec_version=spec["version"],
        light_path=spec["light"]["path"]["value"],
        dark_path=spec["dark"]["path"]["value"],
        agent_2=ramp[2],
        agent_ramp="\n".join(f'    "{color}",' for color in ramp),
        fonts="\n".join(
            f'    "{key}": "{value["value"]}",' for key, value in spec["font"].items()
        ),
        light=_scheme(spec, "light"),
        dark=_scheme(spec, "dark"),
    )


def _diff(expected: str, actual: str, path: Path) -> str:
    return "".join(
        difflib.unified_diff(
            actual.splitlines(keepends=True),
            expected.splitlines(keepends=True),
            fromfile=f"{path.name} (vendored)",
            tofile=f"{path.name} (branding)",
        )
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="python scripts/sync_tokens.py", description=__doc__.splitlines()[0]
    )
    parser.add_argument(
        "--source",
        default=DEFAULT_SOURCE,
        help="URL prefix or local branding checkout (default: the branding repo)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; exit 1 if the vendored copy has drifted",
    )
    args = parser.parse_args(argv)

    spec = json.loads(_read(args.source, "tokens.json"))
    wanted = {
        TOKENS_PY: render(spec),
        MPLSTYLE: _read(args.source, "frontier.mplstyle"),
    }

    if args.check:
        drifted = False
        for path, expected in wanted.items():
            actual = path.read_text(encoding="utf-8") if path.exists() else ""
            if actual != expected:
                drifted = True
                print(f"::error::{path.relative_to(REPO)} has drifted from branding")
                print(_diff(expected, actual, path))
        if drifted:
            print("\nRun `python scripts/sync_tokens.py` and commit the result.")
            return 1
        print(f"tokens in sync with branding {spec['version']} ({args.source})")
        return 0

    for path, text in wanted.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        print(f"wrote {path.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
